public let highlightLanguages: [String: String] = [
    "1c": "1C",
    "accesslog": "Access log",
    "actionscript": "ActionScript",
    "ada": "Ada",
    "apache": "Apache",
    "applescript": "AppleScript",
    "arduino": "Arduino",
    "armasm": "ARM Assembly",
    "asciidoc": "AsciiDoc",
    "aspectj": "AspectJ",
    "autohotkey": "AutoHotkey",
    "autoit": "AutoIt",
    "avrasm": "AVR Assembler",
    "awk": "Awk",
    "axapta": "Axapta",
    "bash": "Bash",
    "basic": "Basic",
    "brainfuck": "Brainfuck",
    "ceylon": "Ceylon",
    "clean": "Clean",
    "clojure-repl": "Clojure REPL",
    "clojure": "Clojure",
    "cmake": "CMake",
    "coffeescript": "CoffeeScript",
    "coq": "Coq",
    "cpp": "C++",
    "crmsh": "crmsh",
    "crystal": "Crystal",
    "cs": "C#",
    "csp": "CSP",
    "css": "CSS",
    "d": "D",
    "dart": "Dart",
    "delphi": "Delphi",
    "diff": "Diff",
    "django": "Django",
    "dns": "DNS Zone file",
    "dockerfile": "Dockerfile",
    "dsconfig": "dsconfig",
    "dts": "Device Tree",
    "dust": "Dust",
    "elixir": "Elixir",
    "elm": "Elm",
    "erlang-repl": "Erlang REPL",
    "erlang": "Erlang",
    "excel": "Excel",
    "fix": "FIX",
    "flix": "Flix",
    "fortran": "Fortran",
    "fsharp": "F#",
    "gams": "GAMS",
    "gauss": "GAUSS",
    "gherkin": "Gherkin",
    "glsl": "GLSL",
    "go": "Go",
    "golo": "Golo",
    "gradle": "Gradle",
    "groovy": "Groovy",
    "haml": "Haml",
    "handlebars": "Handlebars",
    "haskell": "Haskell",
    "haxe": "Haxe",
    "hsp": "HSP",
    "htmlbars": "HTMLBars",
    "http": "HTTP",
    "hy": "Hy",
    "inform7": "Inform 7",
    "ini": "Ini",
    "irpf90": "IRPF90",
    "java": "Java",
    "javascript": "JavaScript",
    "json": "JSON",
    "julia": "Julia",
    "kotlin": "Kotlin",
    "lasso": "Lasso",
    "ldif": "LDIF",
    "leaf": "Leaf",
    "less": "Less",
    "lisp": "Lisp",
    "livecodeserver": "LiveCode",
    "livescript": "LiveScript",
    "llvm": "LLVM IR",
    "lsl": "Linden Scripting Language",
    "lua": "Lua",
    "makefile": "Makefile",
    "markdown": "Markdown",
    "mathematica": "Mathematica",
    "matlab": "Matlab",
    "maxima": "Maxima",
    "mel": "MEL",
    "mercury": "Mercury",
    "mipsasm": "MIPS Assembly",
    "mizar": "Mizar",
    "mojolicious": "Mojolicious",
    "monkey": "Monkey",
    "moonscript": "MoonScript",
    "nginx": "Nginx",
    "nimrod": "Nimrod",
    "nix": "Nix",
    "nsis": "NSIS",
    "ocaml": "OCaml",
    "openscad": "OpenSCAD",
    "oxygene": "Oxygene",
    "parser3": "Parser3",
    "perl": "Perl",
    "pf": "pf",
    "php": "PHP",
    "pony": "Pony",
    "powershell": "PowerShell",
    "processing": "Processing",
    "profile": "Python profile",
    "prolog": "Prolog",
    "protobuf": "Protocol Buffers",
    "puppet": "Puppet",
    "purebasic": "PureBASIC",
    "python": "Python",
    "q": "Q",
    "qml": "QML",
    "r": "R",
    "rib": "RenderMan RIB",
    "roboconf": "Roboconf",
    "rsl": "RenderMan RSL",
    "ruby": "Ruby",
    "ruleslanguage": "Oracle Rules Language",
    "rust": "Rust",
    "scala": "Scala",
    "scheme": "Scheme",
    "scilab": "Scilab",
    "scss": "SCSS",
    "smali": "Smali",
    "smalltalk": "Smalltalk",
    "sml": "SML",
    "sqf": "SQF",
    "sql": "SQL",
    "stan": "Stan",
    "stata": "Stata",
    "step21": "STEP Part 21",
    "stylus": "Stylus",
    "subunit": "SubUnit",
    "swift": "Swift",
    "taggerscript": "Tagger Script",
    "tap": "Test Anything Protocol",
    "tcl": "Tcl",
    "tex": "TeX",
    "thrift": "Thrift",
    "tp": "TP",
    "twig": "Twig",
    "typescript": "TypeScript",
    "vala": "Vala",
    "vbscript-html": "VBScript in HTML",
    "vbscript": "VBScript",
    "verilog": "Verilog",
    "vhdl": "VHDL",
    "vim": "Vim Script",
    "x86asm": "Intel x86 Assembly",
    "xl": "XL",
    "xquery": "XQuery",
    "yaml": "YAML",
    "zephir": "Zephir",
]

public let highlightStyles: [String: String] = [
    "agate": "Agate",
    "androidstudio": "Androidstudio",
    "arduino-light": "Arduino Light",
    "arta": "Arta",
    "ascetic": "Ascetic",
    "atelier-cave-dark": "Atelier Cave Dark",
    "atelier-cave-light": "Atelier Cave Light",
    "atelier-dune-dark": "Atelier Dune Dark",
    "atelier-dune-light": "Atelier Dune Light",
    "atelier-estuary-dark": "Atelier Estuary Dark",
    "atelier-estuary-light": "Atelier Estuary Light",
    "atelier-forest-dark": "Atelier Forest Dark",
    "atelier-forest-light": "Atelier Forest Light",
    "atelier-heath-dark": "Atelier Heath Dark",
    "atelier-heath-light": "Atelier Heath Light",
    "atelier-lakeside-dark": "Atelier Lakeside Dark",
    "atelier-lakeside-light": "Atelier Lakeside Light",
    "atelier-plateau-dark": "Atelier Plateau Dark",
    "atelier-plateau-light": "Atelier Plateau Light",
    "atelier-savanna-dark": "Atelier Savanna Dark",
    "atelier-savanna-light": "Atelier Savanna Light",
    "atelier-seaside-dark": "Atelier Seaside Dark",
    "atelier-seaside-light": "Atelier Seaside Light",
    "atelier-sulphurpool-dark": "Atelier Sulphurpool Dark",
    "atelier-sulphurpool-light": "Atelier Sulphurpool Light",
    "atom-one-dark": "Atom One Dark",
    "atom-one-light": "Atom One Light",
    "brown-paper": "Brown Paper",
    "codepen-embed": "Codepen Embed",
    "color-brewer": "Color Brewer",
    "darcula": "Darcula",
    "dark": "Dark",
    "darkula": "Darkula",
    "default": "Default",
    "docco": "Docco",
    "dracula": "Dracula",
    "far": "Far",
    "foundation": "Foundation",
    "github-gist": "Github Gist",
    "github": "Github",
    "googlecode": "Googlecode",
    "grayscale": "Grayscale",
    "gruvbox-dark": "Gruvbox Dark",
    "gruvbox-light": "Gruvbox Light",
    "hopscotch": "Hopscotch",
    "hybrid": "Hybrid",
    "idea": "Idea",
    "ir-black": "Ir Black",
    "kimbie.dark": "Kimbie.dark",
    "kimbie.light": "Kimbie.light",
    "magula": "Magula",
    "mono-blue": "Mono Blue",
    "monokai-sublime": "Monokai Sublime",
    "monokai": "Monokai",
    "obsidian": "Obsidian",
    "ocean": "Ocean",
    "paraiso-dark": "Paraiso Dark",
    "paraiso-light": "Paraiso Light",
    "pojoaque": "Pojoaque",
    "purebasic": "Purebasic",
    "qtcreator_dark": "Qtcreator Dark",
    "qtcreator_light": "Qtcreator Light",
    "railscasts": "Railscasts",
    "rainbow": "Rainbow",
    "school-book": "School Book",
    "solarized-dark": "Solarized Dark",
    "solarized-light": "Solarized Light",
    "sunburst": "Sunburst",
    "tomorrow-night-blue": "Tomorrow Night Blue",
    "tomorrow-night-bright": "Tomorrow Night Bright",
    "tomorrow-night-eighties": "Tomorrow Night Eighties",
    "tomorrow-night": "Tomorrow Night",
    "tomorrow": "Tomorrow",
    "vs": "Vs",
    "xcode": "Xcode",
    "xt256": "Xt256",
    "zenburn": "Zenburn",
]
